title: "Geolexica"

committee:
  id: 211
  name: Geographic information/Geomatics
  link: https://committee.iso.org/home/tc211

email: open.source@ribose.com

tagline: >-
  The authoritative
  geographic information terminology database

description: >-
  The authoritative glossary for geographic information technology from ISO/TC 211.

baseurl: ""
url: "https://geolexica.com"

social:
  links:
    - url: https://twitter.com/ISOTC211
    - url: https://github.com/ISO-TC211
    - url: https://www.facebook.com/groups/236669159734679/
    - url: https://www.linkedin.com/groups/4222374

# algolia:
#   application_id: NOP
#   index_name: NOP
#   search_only_api_key: NOP

nav:
  home:
    url: /
    title: Home
  about:
    url: /about
    title: About
  concepts:
    url: /concepts
    title: Concepts
  stats:
    url: /stats
    title: Statistics

footer_nav:
  - url: https://committee.iso.org/home/tc211
    title: ISO/TC 211

powered_by:
  url: https://open.ribose.com
  title: Ribose
  logo_path: /assets/logo-ribose.svg

theme: jekyll-theme-isotc211

sass:
  style: compressed

collections:
  pages:
    output: true
    permalink: /:path/
  concepts:
    output: true
    permalink: /:collection/:name/
  concepts_json:
    output: true
    output_ext: .json
    permalink: /api/concepts/:name.json

defaults:
  - scope:
      path: ""
      type: "concepts"
    values:
      layout: concept
  - scope:
      path: ""
      type: "concepts_json"
    values:
      layout: concept.json
      permalink: /api/concepts/:name.json

term_languages:
  - eng
  - spa
  - ara
  - chi
  - dan
  - fin
  - fre
  - ger
  - jpn
  - kor
  - rus
  - swe

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - deploy.sh
  - "*.xlsx"
  - "*.yaml"
  - concepts_data
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/
