title: "Geolexica"

email: open.source@ribose.com

description: >-
  Welcome to Geolexica, the authoritative glossary for geographic
  information technology from ISO/TC 211.

baseurl: ""
url: "https://geolexica.com"

social:
  links:
    - https://twitter.com/ISOTC211
    - https://github.com/ISO-TC211
    - https://www.iso.org/committee/54904.html#meetings
    - https://www.facebook.com/groups/236669159734679/
    - https://www.linkedin.com/groups/4222374

# TODO add these
# https://www.iso.org/committee/54904.html#meetings
# https://www.facebook.com/groups/236669159734679/
# https://www.linkedin.com/groups/4222374


markdown: kramdown

# TODO: Move styling into theme
#theme: isotc211

plugins:
  - jekyll-feed

sass:
  style: compressed

collections:
  pages:
    output: true
    permalink: /:path/
  concepts:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: "concepts"
    values:
      layout: concept

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - deploy.sh
  - "*.xlsx"
  - "*.yaml"
  - concepts_data
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
